root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react-hooks
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  curly: error
  no-return-await: error
  prefer-arrow-callback: error
  prettier/prettier:
    - error
    - arrowParens: always
      semi: false
      singleQuote: true
      trailingComma: all
      tabWidth: 2
  react/prop-types: off
  react/display-name: off
  require-await: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
settings:
  react:
    version: detect
