name: test pr

on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # unit test
      - name: Run tests
        run: yarn test:unit

      # integration test ( also tests build success)
      - name: Install Playwright
        run: yarn add playwright@1.29.1
      - name: Install Playwright Browsers
        run: npx playwright@1.29.1 install --with-deps # note: package.json 과 버전 맞춰야 함
      - name: Build Application
        run: docker build -t snutt-ev-web-pr-test --build-arg APP_ENV=test .
      - name: Start Application
        run: docker run -dp 3000:3000 snutt-ev-web-pr-test
      - name: Run Playwright tests
        run: yarn test:e2e
